--liquibase formatted sql

--changeset codex:002-mvp-schema context:all labels:mvp
--comment Esquema MVP inicial para calendarios SECOT con PK tecnicas numericas y claves funcionales separadas.

create table senior (
    id bigint generated by default as identity primary key,
    senior_codigo integer not null,
    nombre varchar(100) not null,
    apellido1 varchar(100) not null,
    apellido2 varchar(100),
    email_personal varchar(150),
    email_secot varchar(150),
    movil varchar(20),
    fecha_alta date,
    activo boolean not null default true,
    constraint uq_senior_codigo unique (senior_codigo),
    constraint uq_senior_email_secot unique (email_secot),
    constraint ck_senior_codigo_positivo check (senior_codigo > 0),
    constraint ck_senior_fecha_alta check (fecha_alta is null or fecha_alta >= date '2020-01-01')
);

create table grupo (
    id bigint generated by default as identity primary key,
    grupo_codigo integer not null,
    nombre_grupo varchar(120) not null,
    descripcion varchar(1000),
    color_hex varchar(7) not null,
    canal_teams varchar(120),
    responsable_senior_id bigint not null,
    activo boolean not null default true,
    constraint uq_grupo_codigo unique (grupo_codigo),
    constraint uq_grupo_nombre_grupo unique (nombre_grupo),
    constraint ck_grupo_codigo_positivo check (grupo_codigo > 0),
    constraint ck_grupo_color_hex check (color_hex ~ '^#[0-9A-Fa-f]{6}$'),
    constraint fk_grupo_responsable_senior
        foreign key (responsable_senior_id) references senior (id)
);

create table centro (
    id bigint generated by default as identity primary key,
    centro_codigo integer not null,
    nombre_centro varchar(150) not null,
    tipo_centro varchar(20) not null,
    direccion varchar(255),
    municipio varchar(100),
    responsable_centro varchar(150),
    email_responsable varchar(150),
    telefono_responsable varchar(20),
    observaciones varchar(1000),
    activo boolean not null default true,
    constraint uq_centro_codigo unique (centro_codigo),
    constraint uq_centro_nombre_centro unique (nombre_centro),
    constraint ck_centro_codigo_positivo check (centro_codigo > 0),
    constraint ck_centro_tipo check (tipo_centro in ('Mayores', 'Ensenanza', 'Asociacion', 'Otro'))
);

create table actividad (
    id bigint generated by default as identity primary key,
    actividad_codigo integer not null,
    grupo_id bigint not null,
    centro_id bigint not null,
    titulo_actividad varchar(200) not null,
    descripcion varchar(1500),
    tipo_actividad varchar(20) not null,
    senior_responsable_id bigint not null,
    estado_actividad varchar(20) not null,
    fecha_inicio_prevista date,
    fecha_fin_prevista date,
    activo boolean not null default true,
    constraint uq_actividad_codigo unique (actividad_codigo),
    constraint ck_actividad_codigo_positivo check (actividad_codigo > 0),
    constraint ck_actividad_tipo check (tipo_actividad in ('Taller', 'Charla', 'Mentoria', 'Reunion', 'Otra')),
    constraint ck_actividad_estado check (estado_actividad in ('Borrador', 'Planificada', 'EnCurso', 'Finalizada', 'Cancelada')),
    constraint ck_actividad_fechas check (
        fecha_inicio_prevista is null
        or fecha_fin_prevista is null
        or fecha_fin_prevista >= fecha_inicio_prevista
    ),
    constraint fk_actividad_grupo
        foreign key (grupo_id) references grupo (id),
    constraint fk_actividad_centro
        foreign key (centro_id) references centro (id),
    constraint fk_actividad_senior_responsable
        foreign key (senior_responsable_id) references senior (id)
);

create table senior_grupo (
    id bigint generated by default as identity primary key,
    senior_grupo_codigo integer not null,
    senior_id bigint not null,
    grupo_id bigint not null,
    rol_en_grupo varchar(20) not null,
    fecha_alta date,
    fecha_baja date,
    activo boolean not null default true,
    constraint uq_senior_grupo_codigo unique (senior_grupo_codigo),
    constraint uq_senior_grupo_relacion unique (senior_id, grupo_id),
    constraint ck_senior_grupo_codigo_positivo check (senior_grupo_codigo > 0),
    constraint ck_senior_grupo_rol check (rol_en_grupo in ('Responsable', 'Coordinador', 'Miembro')),
    constraint ck_senior_grupo_fechas check (
        fecha_alta is null
        or fecha_baja is null
        or fecha_baja >= fecha_alta
    ),
    constraint fk_senior_grupo_senior
        foreign key (senior_id) references senior (id),
    constraint fk_senior_grupo_grupo
        foreign key (grupo_id) references grupo (id)
);

create table actividad_senior (
    id bigint generated by default as identity primary key,
    actividad_senior_codigo integer not null,
    actividad_id bigint not null,
    senior_id bigint not null,
    rol_en_actividad varchar(20) not null,
    fecha_alta date,
    fecha_baja date,
    activo boolean not null default true,
    constraint uq_actividad_senior_codigo unique (actividad_senior_codigo),
    constraint uq_actividad_senior_relacion unique (actividad_id, senior_id),
    constraint ck_actividad_senior_codigo_positivo check (actividad_senior_codigo > 0),
    constraint ck_actividad_senior_rol check (rol_en_actividad in ('Responsable', 'Coordinador', 'Participante')),
    constraint ck_actividad_senior_fechas check (
        fecha_alta is null
        or fecha_baja is null
        or fecha_baja >= fecha_alta
    ),
    constraint fk_actividad_senior_actividad
        foreign key (actividad_id) references actividad (id),
    constraint fk_actividad_senior_senior
        foreign key (senior_id) references senior (id)
);

create table sesion (
    id bigint generated by default as identity primary key,
    sesion_codigo integer not null,
    actividad_id bigint not null,
    grupo_id bigint not null,
    centro_id bigint not null,
    fecha date not null,
    hora_inicio timestamp without time zone not null,
    hora_fin timestamp without time zone not null,
    duracion_horas numeric(4,2),
    titulo_sesion varchar(200) not null,
    ubicacion varchar(150),
    estado_sesion varchar(20) not null,
    observaciones varchar(1500),
    es_visible_calendario boolean not null default true,
    activo boolean not null default true,
    constraint uq_sesion_codigo unique (sesion_codigo),
    constraint ck_sesion_codigo_positivo check (sesion_codigo > 0),
    constraint ck_sesion_estado check (estado_sesion in ('Pendiente', 'Confirmada', 'Realizada', 'Cancelada')),
    constraint ck_sesion_horas check (hora_fin > hora_inicio),
    constraint ck_sesion_duracion check (duracion_horas is null or (duracion_horas >= 1 and duracion_horas <= 3)),
    constraint ck_sesion_fecha_hora_inicio check (hora_inicio::date = fecha),
    constraint ck_sesion_fecha_hora_fin check (hora_fin::date = fecha),
    constraint fk_sesion_actividad
        foreign key (actividad_id) references actividad (id),
    constraint fk_sesion_grupo
        foreign key (grupo_id) references grupo (id),
    constraint fk_sesion_centro
        foreign key (centro_id) references centro (id)
);

create index idx_grupo_responsable_senior_id on grupo (responsable_senior_id);
create index idx_actividad_grupo_id on actividad (grupo_id);
create index idx_actividad_centro_id on actividad (centro_id);
create index idx_actividad_senior_responsable_id on actividad (senior_responsable_id);
create index idx_senior_grupo_senior_id on senior_grupo (senior_id);
create index idx_senior_grupo_grupo_id on senior_grupo (grupo_id);
create index idx_actividad_senior_actividad_id on actividad_senior (actividad_id);
create index idx_actividad_senior_senior_id on actividad_senior (senior_id);
create index idx_sesion_actividad_id on sesion (actividad_id);
create index idx_sesion_grupo_id on sesion (grupo_id);
create index idx_sesion_centro_id on sesion (centro_id);
create index idx_sesion_fecha on sesion (fecha);
