--liquibase formatted sql

--changeset codex:003-auth-users context:all labels:auth
--comment Capa de autenticacion basica: tabla de usuarios (credenciales) para login JWT.

create table app_user (
    id bigint generated by default as identity primary key,
    username varchar(80) not null,
    password_salt_b64 varchar(64) not null,
    password_hash_b64 varchar(64) not null,
    is_active boolean not null default true,
    created_at timestamp without time zone not null default now(),
    constraint uq_app_user_username unique (username)
);

-- Usuario inicial para el MVP (cambiar credenciales en produccion).
-- Password: admin123
insert into app_user (username, password_salt_b64, password_hash_b64, is_active)
values ('admin', '+RtITgboIqZmDGaYDBF0hw==', 'jHMbEkf/bIxM98phy2SlFSiVn34rezWXB3Gn2IR+qE8=', true);

